### ISSUE TITLE
Should I be able to add a negative number as an input?

### ISSUE THREAD

**Issue by AlexKap23** [dccl90/NumberGuessingGame#2]
https://github.com/dccl90/NumberGuessingGame/blob/5713bca6700acf16d49689fdfd059e0eac9c3053/NumberGuessingGame/Program.cs#L20

I have provided a negative number as an input. The program worked as if it was positive. Is this a behaviour you want your program to have?

**Comment by dccl90** [comment]
Fixed negative input
