### ISSUE TITLE
This is also a magic number

### ISSUE THREAD

**Issue by AlexKap23** [dccl90/NumberGuessingGame#3]
https://github.com/dccl90/NumberGuessingGame/blob/d93dce6e982074879ce2f0de126168e350057040/NumberGuessingGame/Program.cs#L19

Since you have defined your range, you can replace all numbers inside your code with constants. Check also the messages as by utilizing constants in the messages you can change your range and you just have to change 2 constants and not look the whole code base.

**Comment by dccl90** [comment]
Removed magic number
